config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin}
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do

  constraints SubdomainConstraint do
    get    'sessions/new'
    
    root                 'routes#show'
    get    'contact'        => 'static_pages#contact'     
    get    'login'          => 'sessions#new'
    post   'login'          => 'sessions#create'
    delete 'logout'         => 'sessions#destroy'
    post   'search'         => 'routes#search'
    post   'cancel'         => 'tickets#cancel_passenger'
    post   'passenger_list' => 'passengers#new'
    

    resources :places, :only => [:new, :create, :index] 
    resources :routes, :only => [:new, :create, :show, :index]
    resources :users
    resources :passengers, :only => [:create] 
    resources :tickets, :only => [:index, :show] 
  end

  resources :accounts
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #do we really need these action declarations.....?
  def home
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1>
<center>
<table>
	<tr>
		<td><b>FreshBus</b></td>
	</tr>
	<tr>
		<td>First Floor,</td>
	</tr> 
	<tr>
		<td>Block B, SP Infocity,</td>
	</tr> 
	<tr>
		<td>40 MGR Salai,</td>
	</tr> 
	<tr>
		<td>Perungudi,</td>
	</tr> 
	<tr>
		<td>Chennai,</td>
	</tr> 
	<tr>
		<td>Tamil Nadu 600096</td>
	</tr>
	<tr>
		<td>Phone:+1 866-832-3090</td>
	</tr>
</table>

</center>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	redirect_to root_path
<%   else %>
   <div class="center jumbotron"\>
  <h1>Welcome to FreshBus Service</h1>
  <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>